### PR TITLE
GitHub Actions CI

### PR DESCRIPTION
**Pull request by sorki**
Using my hopefully temporary fork of https://github.com/vmchale/github-actions-dhall

from https://github.com/vmchale/github-actions-dhall/compare/master...sorki:pending

Build steps needs filtering but it quickly gets ugly due to
https://github.com/dhall-lang/dhall-lang/issues/961 so we hack around
this and instead do `init` on build steps which just leaves out `haddoc`
step.

--

I've noticed that this is still using Travis, so gave it a shot, using dhall for some additional dogfooding :smile:

### CODE REVIEW

**Comment by sorki** [comment]
Passing run https://github.com/sorki/nix-diff/actions/runs/670820826

**Comment by Gabriel439** [comment]
@sorki: I will turn off the Travis integration in favor of the GitHub actions

**Comment by sorki** [comment]
Cool! I'll PR similar one to `nix-derivation`

**Comment by Gabriel439** [comment]
Sounds good 🙂

**Pull request merged**
