### PR TITLE
nix-derivation 1.1 changes

### PR DESCRIPTION
**Pull request by sorki**
ssia

### CODE REVIEW

**Comment by Gabriel439** [comment]
@sorki: Alright, I just uploaded `nix-derivation-1.1.0` to Hackage, so now this pull request just needs to be updated to refer to that

**Comment by sorki** [comment]
Updated with Nix file changes similar to `nix-derivation`. I've added the `nix-derivation-1.1` reference to the last commit, the commit before also references https://github.com/Gabriel439/Haskell-Nix-Derivation-Library/pull/4

Looks like that CI is not happy about the bumped dependency though, maybe just needs a bump.

**Comment by Gabriel439** [comment]
@sorki: I think it's because CI is building against an older version of GHC because it's using an old `.travis.yml` from back before I switched this project to use Nix.  If you change the `.travis.yml` to match the Nix-based one that the `nix-derivation` project uses then I think the CI problems will go away:

https://github.com/Gabriel439/Haskell-Nix-Derivation-Library/blob/3f95b84acc5e98865d98817b8b0aa73b7750c5f9/.travis.yml

**Comment by sorki** [comment]
Yup, looks better now, it will start passing when Haskell package set is update in NixOS.

**Comment by sorki** [comment]
Btw I've noticed some libraries are using http://hackage.haskell.org/packages/#cat:Nix - what do you think of switching categories of this and `nix-derivation` from System to Nix?

**Comment by peti** [comment]
`nix-diff` is broken in current versions of `master` because we have the new version of `nix-derivation` already but it's not supported yet.

**Comment by Gabriel439** [comment]
@peti: Don't worry, I'm not going to wait until Nixpkgs updates to get this through our CI.  I will get this to Hackage soon

**Comment by Gabriel439** [comment]
@sorki: If you merge https://github.com/sorki/nix-diff/pull/1 into your branch I believe it will fix the CI build failure

**Comment by sorki** [comment]
Thanks, it didn't occur to me to add the overlay for CI.

**Comment by Gabriel439** [comment]
You're welcome!

**Pull request merged**
