### PR TITLE
Output all differences between the compared derivations

### LINKED ISSUE #5: Missing differences when input names do not match
I have just changed my local overlay, resulting in something like:
```nix
todiff = super.rustPlatform.buildRustPackage rec {
  name = "todiff-${version}";
  version = "0.2.1";

  src = super.fetchFromGitHub {
    owner = "Ekleog";
    repo = "todiff";
    rev = version;
    sha256 = "145l3wyk4z5m5n7vvz0wdgpp7f1l3jzmq9mvpmbb7lr2cqy1x7mw";
  };

  cargoSha256 = "0mxdpn98fvmxrp656vwxvzl9vprz5mvqj7d1hvvs4gsjrsiyp0fy";

  meta = with super.stdenv.lib; {
    description = "Human-readable diff for todo.txt files";
    homepage = "https://github.com/Ekleog/todiff";
    platforms = platforms.all;
  };
};

topydo = super.topydo.overrideAttrs (_: {
  src = super.fetchFromGitHub {
    owner = "Ekleog";
    repo = "topydo";
    rev = "51296f809cf5325d93dd284229cc49cb2471df6e";
    sha256 = "03cfwbp8ps6gzgmrajqz9yf5824pa9j5hcignavm4qgkld5fdlzz";
  };
});
```

With the changes to `todiff` being an update, and the changes to `topydo` being that I just added the override.

With this, running `nix-diff` between the two systems, I only get the following (skipping irrelevant portions):
```
• The input named `etc` differs
  - /nix/store/givj3m8i2kacdbh3fa7bgiii7avvf3vw-etc.drv:{out}
  + /nix/store/w5h8rcy4xarc6lfxzpkzd3g4l26fvsyp-etc.drv:{out}
  • The input named `dbus-1` differs
    - /nix/store/95d4nnaillhq8clhkz639fsp746688af-dbus-1.drv:{out}
    + /nix/store/j1pdwb3jj7nqdjzh92wr7iklhrs2ij55-dbus-1.drv:{out}
    • The input named `system-path` differs
      - /nix/store/0880pnwzkqw9yy1cb8s63ligmkgla7kb-system-path.drv:{out}
      + /nix/store/xy75g7rpaprz7lnjv14xf40iiz45n60i-system-path.drv:{out}
      • The set of input names do not match:
          - todiff-0.1.1
          + todiff-0.2.1
  • The input named `system-path` differs
    • These two derivations have already been compared
```

So the diff on `topydo` is missed -- and I checked it did change:
```
$ ls -lah result/sw/bin/topydo
lrwxrwxrwx 2 root root 66 Jan  1  1970 result/sw/bin/topydo -> /nix/store/iz38bx5hdngbancplndy2vgxxikvblw2-topydo-0.13/bin/topydo
$ ls -lah /run/current-system/sw/bin/topydo
lrwxrwxrwx 5 root root 66 Jan  1  1970 /run/current-system/sw/bin/topydo -> /nix/store/xmbhia0i7gkg67adhi3pb4d897k6d7qm-topydo-0.13/bin/topydo
```

The `nix-diff` being run this way, I think it should have detected the change:
```
nix-diff $(nix-store -q --deriver $(readlink /run/current-system)) $(nix-store -q --deriver $(readlink result))
```

I would guess the reason is that there is both an input name change and another change: undoing my changes to the `todiff` package allowed the changes to `topydo` to appear.

Hope that's at least a bit clear! I wasn't sure how to go with explaining the issue…

### PR DESCRIPTION
**Pull request by Ekleog**
Before this change, if the set of input names to a derivation changed,
then the set of matching-names inputs was not compared.

This fixes the issue, allowing to use `nix-diff` as a tool for system
administration: there, you have to know all the differences between the
two system derivations, not only until an input set has a mismatching
name (eg. a linux-kernel upgrade should not hide an nginx upgrade).

Fixes #5.

### CODE REVIEW

**Comment by Ekleog** [comment]
For ease of reviewing, the changes here are:
 * Change the `if leftNames /= rightNames then A else B` in `when (leftNames /= rightNames) A >>= B` to not shortcut (which means the indentation change that makes the diff hard to read)
 * Remove 4 trailing spaces I noticed when doing this diff

**Comment by Gabriel439** [comment]
Awesome!  Thanks for doing this :)

**Comment by Ekleog** [comment]
And thanks for accepting it! :)

**Comment by Gabriel439** [comment]
You're welcome! :)

**Pull request merged**
